### ISSUE TITLE
Result summary / overview undefined.

### ISSUE THREAD

**Issue by yeban** [wurmlab/genevalidatorapp#14]
... after the latest changes. See screenshot.
![screen shot 2015-07-27 at 11 10 47 am](https://cloud.githubusercontent.com/assets/90373/8899301/475668c0-3450-11e5-96d7-3a983dc25820.png)

**Comment by IsmailM** [comment]
It was working fine for me yesterday. I'll double check again today. I think this is because:

The gem versions of gv and gv app on ruby gems  are quite old. I think you need to manually install the latest version of gv (js branch) and then `bundle install --local` Genevalidatorapp...

**Comment by IsmailM** [comment]
Just checked and In retrospect, I may have merged the latest PR too early...

The latest version of GVapp on Github currently only works with the latest version of GV. As a result, you currently need to manually install the latest versions of GV and GVapp from Github...  

Once wurmlab/genevalidator#94 has been merged, I'll push updated gems for GV/GVapp to rubygems.org...

**Comment by IsmailM** [comment]
I have pushed updated GV and GVapp gems to rubygems.org

Everything should work as expected...
