### ISSUE TITLE
results overview - problem with score distribution plot 

### ISSUE THREAD

**Issue by monicadragan** [wurmlab/genevalidatorapp#18]
![screenshot from 2015-08-01 12 16 57](https://cloud.githubusercontent.com/assets/4270488/9021547/7f73c892-3847-11e5-9c77-8d20e5619798.png)

It seems that the score distribution plot doesn't update according to the input data - this happend in the webapp (see above) and not when GV is run in cmdline

**Comment by IsmailM** [comment]
Well spotted...

In actual fact, all the plots/ explanations were from initial analysis and did not update - so this would have been a major issue...

Fixed via 9bde545

Have pushed an updated gem (version 1.5.1). Will be updating [genevalidator.sbcs.qmul.ac.uk](http://genevalidator.sbcs.qmul.ac.uk) shortly.
