### ISSUE TITLE
Non-executable files set with executable permissions

### ISSUE THREAD

**Issue by mensfeld** [wurmlab/genevalidatorapp#27]
Hey there,

My name is Maciej Mensfeld and I run a security research project https://diffend.io

While reviewing the source code of `genevalidatorapp` I've noticed, that several files in the `data/public/web_files` directory have executable permissions while not being an executables.

For example:

```
public/web_files/fonts/fontawesome-webfont.woff
public/web_files/fonts/fontawesome-webfont.ttf
public/web_files/fonts/fontawesome-webfont.svg
public/web_files/img/gene.png
```
is that something intended? If so, I would appreciate an explanation as I often find it a bug.

Thank you :pray:

**Comment by IsmailM** [comment]
Thanks - this should now be fixed
