### ISSUE TITLE
Thin drops request after 30s.

### ISSUE THREAD

**Issue by yeban** [wurmlab/genevalidatorapp#9]
That's the default behaviour. This is preventing http://genevalidator.sbcs.qmul.ac.uk/ from running even 10 queries at once.

**Comment by yeban** [comment]
Perhaps adding `server.timeout = 180` after [L62](https://github.com/IsmailM/GeneValidatorApp/blob/master/lib/GeneValidatorApp.rb#L62) will do the trick. The value should be in seconds.

You could make this configurable or just set a higher default. (Or you could go back to webrick - https://github.com/yannickwurm/sequenceserver/commit/508e7155750f8ef7a97c4aba58dcc8a75878481)

**Comment by IsmailM** [comment]
For the moment I have simply inserted the a `server.timeout` of 45 mins (2700 seconds). (however I haven't tested if this works)...

After my exams, I will probably follow SequenceServer and go back to Webrick...

I have updated and restarted GVapp on the Nuc

**Comment by IsmailM** [comment]
Actually, since this untested, I'm reopening... 

I'll close once I (or someone else) has tested it...

**Comment by IsmailM** [comment]
No longer thin... No using WebBRICK....

But still need to test this...

**Comment by yeban** [comment]
This does seem to work for me locally. Would like to test on http://genevalidator.sbcs.qmul.ac.uk/ before closing it.
